
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

language: cpp

compiler:
  - clang
  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS:BOOL=1 ..
  - make
  - ./bin/asv-tests
branches:
  only:
  - cc
            
    
