
sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS:BOOL=1 ..
  - make
  - ./bin/asv-tests

notifications:
  irc: "chat.freenode.net#asv"
      
